name: Deploy to VPS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t 314zet-web .

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/[nazwa_projektu]
            docker build -t 314zet-web .
            docker stop 314zet-web-container || true
            docker rm 314zet-web-container || true
            docker run -d \
              -p 80:80 \
              --name 314zet-web-container \
              314zet-web