name: Deploy to VPS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # Stwórz katalog projektu jeśli nie istnieje
            mkdir -p /var/www/314zet-web
            cd /var/www/314zet-web
            
            # Sklonuj lub zaktualizuj repozytorium
            if [ -d .git ]; then
              git pull
            else
              git clone https://github.com/profitsky/314zet.git .
            fi
            
            # Zbuduj i uruchom kontener
            docker build -t 314zet-web .
            docker stop 314zet-web-container || true
            docker rm 314zet-web-container || true
            docker run -d \
              -p 80:3000 \
              --restart always \
              --name 314zet-web-container \
              314zet-web