name: Deploy to VPS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            docker build -t 314zet-web https://github.com/profitsky/314zet.git#main
            docker stop 314zet-web-container || true
            docker rm 314zet-web-container || true
            docker run -d \
              -p 3000:3000 \
              --restart always \
              --name 314zet-web-container \
              314zet-web